const fs = require('fs');
const path = require('path');

const VOICE_DIR = path.join(__dirname, '../assets/Voice');
const OUTPUT_FILE = path.join(__dirname, '../src/config/voiceAssets.ts');

// Create config directory if it doesn't exist
const configDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
}

console.log(`Scanning voice directory: ${VOICE_DIR}`);

if (!fs.existsSync(VOICE_DIR)) {
    console.error(`Voice directory not found: ${VOICE_DIR}`);
    process.exit(1);
}

const files = fs.readdirSync(VOICE_DIR);
const audioFiles = files.filter(file => /\.(mp3|wav|ogg|m4a)$/i.test(file));

console.log(`Found ${audioFiles.length} audio files.`);

let content = `// This file is auto-generated by scripts/generateVoiceMap.js
// Do not edit manually

export const VoiceAssets: { [key: string]: any } = {
`;

audioFiles.forEach(file => {
    // Key is filename without extension (e.g., "CRS_0001")
    const key = path.parse(file).name;
    // Path relative to src/config/voiceAssets.ts -> ../../assets/Voice/file
    content += `    "${key}": require('../../assets/Voice/${file}'),\n`;
});

content += `};
`;

fs.writeFileSync(OUTPUT_FILE, content);
console.log(`Successfully generated ${OUTPUT_FILE}`);
